export const roles = ['operator', 'supervisor', 'manager', 'admin'] as const;

export type Role = (typeof roles)[number];

export const permissions = [
  'inventory:read',
  'inventory:adjustments:write',
  'inventory:adjustments:post',
  'inventory:transfers:write',
  'inventory:putaway:write',
  'inventory:putaway:post',
  'inventory:counts:write',
  'inventory:counts:post',
  'inventory:qc:write',
  'inventory:ledger:void',
  'inventory:lpn:write',
  'purchasing:read',
  'purchasing:write',
  'purchasing:approve',
  'purchasing:void',
  'production:read',
  'production:write',
  'production:execute',
  'production:post',
  'outbound:read',
  'outbound:write',
  'outbound:allocate',
  'outbound:post',
  'finance:read',
  'finance:write',
  'finance:approve',
  'compliance:read',
  'compliance:write',
  'compliance:admin',
  'masterdata:read',
  'masterdata:write',
  'planning:read',
  'planning:write',
  'costlayers:read',
  'costlayers:write',
  'reports:read',
  'reports:write',
  'audit:read',
  'admin:reconcile',
  'admin:imports',
  'admin:outbox',
  'admin:health',
  'users:read',
  'users:write'
] as const;

export type Permission = (typeof permissions)[number];

const operatorPermissions = [
  'inventory:read',
  'inventory:transfers:write',
  'inventory:putaway:write',
  'inventory:putaway:post',
  'inventory:counts:write',
  'inventory:qc:write',
  'inventory:lpn:write',
  'purchasing:read',
  'production:read',
  'production:execute',
  'production:post',
  'outbound:read',
  'compliance:read',
  'masterdata:read',
  'planning:read',
  'reports:read'
] as const satisfies readonly Permission[];

const supervisorPermissions = [
  ...operatorPermissions,
  'inventory:adjustments:write',
  'inventory:counts:post',
  'purchasing:write',
  'outbound:write',
  'outbound:allocate',
  'outbound:post',
  'compliance:write',
  'audit:read'
] as const satisfies readonly Permission[];

const managerPermissions = [
  ...supervisorPermissions,
  'inventory:adjustments:post',
  'inventory:ledger:void',
  'purchasing:approve',
  'purchasing:void',
  'production:write',
  'finance:read',
  'finance:write',
  'compliance:admin',
  'masterdata:write',
  'planning:write',
  'costlayers:read',
  'reports:write'
] as const satisfies readonly Permission[];

const adminPermissions = permissions;

export const rolePermissions = {
  operator: operatorPermissions,
  supervisor: supervisorPermissions,
  manager: managerPermissions,
  admin: adminPermissions
} as const satisfies Record<Role, readonly Permission[]>;

const permissionSets: Record<Role, ReadonlySet<Permission>> = {
  operator: new Set(rolePermissions.operator),
  supervisor: new Set(rolePermissions.supervisor),
  manager: new Set(rolePermissions.manager),
  admin: new Set(rolePermissions.admin)
};

export function isRole(value: string | null | undefined): value is Role {
  return roles.includes(value as Role);
}

export function hasPermission(role: string | null | undefined, permission: Permission): boolean {
  if (!isRole(role)) return false;
  return permissionSets[role].has(permission);
}

export type RoutePermissionRule = {
  methods: readonly string[];
  path: string;
  permission: Permission;
};

export const routePermissionRules = [
  { methods: ['POST'], path: '/admin/inventory-ledger/reconcile', permission: 'admin:reconcile' },
  { methods: ['GET'], path: '/admin/inventory-health', permission: 'admin:health' },
  { methods: ['POST'], path: '/admin/outbox/process', permission: 'admin:outbox' },
  { methods: ['POST'], path: '/admin/imports/upload', permission: 'admin:imports' },
  { methods: ['GET'], path: '/admin/imports/:id', permission: 'admin:imports' },
  { methods: ['POST'], path: '/admin/imports/:id/validate', permission: 'admin:imports' },
  { methods: ['POST'], path: '/admin/imports/:id/apply', permission: 'admin:imports' },

  { methods: ['GET'], path: '/audit-log', permission: 'audit:read' },

  { methods: ['POST'], path: '/qc/accept', permission: 'inventory:qc:write' },
  { methods: ['POST'], path: '/qc/reject', permission: 'inventory:qc:write' },
  { methods: ['POST'], path: '/qc/hold-dispositions', permission: 'inventory:qc:write' },
  { methods: ['POST'], path: '/qc-events', permission: 'inventory:qc:write' },
  { methods: ['PATCH'], path: '/ncrs/:id/disposition', permission: 'inventory:qc:write' },

  { methods: ['POST'], path: '/inventory-adjustments', permission: 'inventory:adjustments:write' },
  { methods: ['PUT'], path: '/inventory-adjustments/:id', permission: 'inventory:adjustments:write' },
  { methods: ['DELETE'], path: '/inventory-adjustments/:id', permission: 'inventory:adjustments:write' },
  { methods: ['POST'], path: '/inventory-adjustments/:id/cancel', permission: 'inventory:adjustments:write' },
  { methods: ['POST'], path: '/inventory-adjustments/:id/post', permission: 'inventory:adjustments:post' },
  { methods: ['POST'], path: '/inventory-transfers', permission: 'inventory:transfers:write' },
  { methods: ['POST'], path: '/putaways', permission: 'inventory:putaway:write' },
  { methods: ['POST'], path: '/putaways/:id/post', permission: 'inventory:putaway:post' },
  { methods: ['POST'], path: '/inventory-counts', permission: 'inventory:counts:write' },
  { methods: ['PATCH'], path: '/inventory-counts/:id', permission: 'inventory:counts:write' },
  { methods: ['POST'], path: '/inventory-counts/:id/post', permission: 'inventory:counts:post' },
  { methods: ['POST'], path: '/inventory-movements/:id/void-transfer', permission: 'inventory:ledger:void' },
  { methods: ['POST'], path: '/lpns', permission: 'inventory:lpn:write' },
  { methods: ['PATCH'], path: '/lpns/:id', permission: 'inventory:lpn:write' },
  { methods: ['POST'], path: '/lpns/:id/move', permission: 'inventory:lpn:write' },
  { methods: ['POST'], path: '/lpns/refresh-view', permission: 'inventory:lpn:write' },

  { methods: ['POST'], path: '/purchase-orders', permission: 'purchasing:write' },
  { methods: ['PUT'], path: '/purchase-orders/:id', permission: 'purchasing:write' },
  { methods: ['POST'], path: '/purchase-orders/:id/approve', permission: 'purchasing:approve' },
  { methods: ['POST'], path: '/purchase-order-lines/:id/close', permission: 'purchasing:write' },
  { methods: ['POST'], path: '/purchase-orders/:id/close', permission: 'purchasing:void' },
  { methods: ['DELETE'], path: '/purchase-orders/:id', permission: 'purchasing:void' },
  { methods: ['POST'], path: '/purchase-orders/:id/cancel', permission: 'purchasing:write' },
  { methods: ['POST'], path: '/purchase-order-receipts', permission: 'purchasing:write' },
  { methods: ['DELETE'], path: '/purchase-order-receipts/:id', permission: 'purchasing:void' },
  { methods: ['POST'], path: '/purchase-order-receipts/:id/void', permission: 'purchasing:void' },
  { methods: ['POST'], path: '/purchase-order-receipts/:id/close', permission: 'purchasing:void' },

  { methods: ['POST'], path: '/work-orders', permission: 'production:write' },
  { methods: ['PATCH'], path: '/work-orders/:id', permission: 'production:write' },
  { methods: ['PATCH'], path: '/work-orders/:id/default-locations', permission: 'production:write' },
  { methods: ['POST'], path: '/work-orders/:id/status/:status', permission: 'production:write' },
  { methods: ['POST'], path: '/work-orders/:id/use-active-bom', permission: 'production:write' },
  { methods: ['POST'], path: '/work-orders/:id/disassemble', permission: 'production:post' },
  { methods: ['POST'], path: '/work-orders/:id/issues', permission: 'production:execute' },
  { methods: ['POST'], path: '/work-orders/:id/issues/:issueId/post', permission: 'production:post' },
  { methods: ['POST'], path: '/work-orders/:id/completions', permission: 'production:execute' },
  { methods: ['POST'], path: '/work-orders/:id/completions/:completionId/post', permission: 'production:post' },
  { methods: ['POST'], path: '/work-orders/:id/record-batch', permission: 'production:post' },
  { methods: ['POST'], path: '/work-orders/:id/report-production', permission: 'production:post' },
  { methods: ['POST'], path: '/work-orders/:id/void-report-production', permission: 'production:post' },
  { methods: ['POST'], path: '/work-orders/:id/report-scrap', permission: 'production:post' },
  { methods: ['POST'], path: '/work-orders/:id/reverse', permission: 'production:post' },
  { methods: ['POST'], path: '/boms', permission: 'production:write' },
  { methods: ['POST'], path: '/boms/:id/activate', permission: 'production:write' },
  { methods: ['POST'], path: '/work-centers', permission: 'production:write' },
  { methods: ['PATCH'], path: '/work-centers/:id', permission: 'production:write' },
  { methods: ['POST'], path: '/routings', permission: 'production:write' },
  { methods: ['PATCH'], path: '/routings/:id', permission: 'production:write' },

  { methods: ['POST'], path: '/sales-orders', permission: 'outbound:write' },
  { methods: ['POST'], path: '/reservations', permission: 'outbound:allocate' },
  { methods: ['POST'], path: '/reservations/:id/allocate', permission: 'outbound:allocate' },
  { methods: ['POST'], path: '/reservations/:id/cancel', permission: 'outbound:allocate' },
  { methods: ['POST'], path: '/reservations/:id/fulfill', permission: 'outbound:post' },
  { methods: ['POST'], path: '/shipments', permission: 'outbound:write' },
  { methods: ['POST'], path: '/shipments/:id/post', permission: 'outbound:post' },
  { methods: ['POST'], path: '/returns', permission: 'outbound:write' },
  { methods: ['POST'], path: '/return-receipts', permission: 'outbound:write' },
  { methods: ['POST'], path: '/return-receipts/:id/post', permission: 'outbound:post' },
  { methods: ['POST'], path: '/return-receipts/:id/lines', permission: 'outbound:write' },
  { methods: ['POST'], path: '/return-dispositions', permission: 'inventory:qc:write' },
  { methods: ['POST'], path: '/return-dispositions/:id/post', permission: 'outbound:post' },
  { methods: ['POST'], path: '/return-dispositions/:id/lines', permission: 'inventory:qc:write' },
  { methods: ['POST'], path: '/waves', permission: 'outbound:write' },
  { methods: ['POST'], path: '/pick-batches', permission: 'outbound:write' },
  { methods: ['POST'], path: '/pick-tasks', permission: 'outbound:write' },
  { methods: ['POST'], path: '/shipping-containers', permission: 'outbound:write' },
  { methods: ['POST'], path: '/shipping-containers/:id/items', permission: 'outbound:write' },
  { methods: ['DELETE'], path: '/shipping-containers/:id/items/:itemId', permission: 'outbound:write' },

  { methods: ['POST'], path: '/items', permission: 'masterdata:write' },
  { methods: ['POST'], path: '/items/metrics', permission: 'masterdata:read' },
  { methods: ['PUT'], path: '/items/:id', permission: 'masterdata:write' },
  { methods: ['POST'], path: '/locations', permission: 'masterdata:write' },
  { methods: ['PUT'], path: '/locations/:id', permission: 'masterdata:write' },
  { methods: ['POST'], path: '/locations/templates/standard-warehouse', permission: 'masterdata:write' },
  { methods: ['POST'], path: '/uoms/convert', permission: 'masterdata:read' },
  { methods: ['PATCH'], path: '/items/:id/uom', permission: 'masterdata:write' },
  { methods: ['POST'], path: '/items/:itemId/uom-conversions', permission: 'masterdata:write' },
  { methods: ['DELETE'], path: '/uom-conversions/:id', permission: 'masterdata:write' },

  { methods: ['POST'], path: '/vendors', permission: 'masterdata:write' },
  { methods: ['PUT'], path: '/vendors/:id', permission: 'masterdata:write' },
  { methods: ['DELETE'], path: '/vendors/:id', permission: 'masterdata:write' },
  { methods: ['POST'], path: '/vendor-invoices', permission: 'finance:write' },
  { methods: ['PUT'], path: '/vendor-invoices/:id', permission: 'finance:write' },
  { methods: ['POST'], path: '/vendor-invoices/:id/approve', permission: 'finance:approve' },
  { methods: ['POST'], path: '/vendor-invoices/:id/void', permission: 'finance:approve' },
  { methods: ['POST'], path: '/vendor-payments', permission: 'finance:write' },
  { methods: ['PUT'], path: '/vendor-payments/:id', permission: 'finance:write' },
  { methods: ['POST'], path: '/vendor-payments/:id/post', permission: 'finance:approve' },
  { methods: ['POST'], path: '/vendor-payments/:id/void', permission: 'finance:approve' },

  { methods: ['POST'], path: '/api/cost-layers', permission: 'costlayers:write' },
  { methods: ['POST'], path: '/api/cost-layers/consume', permission: 'costlayers:write' },
  { methods: ['DELETE'], path: '/api/cost-layers/:layerId', permission: 'costlayers:write' },
  { methods: ['POST'], path: '/api/items/:id/roll-cost', permission: 'costlayers:write' },
  { methods: ['POST'], path: '/api/boms/:id/cost-preview', permission: 'costlayers:read' },
  { methods: ['POST'], path: '/api/items/roll-costs', permission: 'costlayers:write' },

  { methods: ['POST'], path: '/mps/plans', permission: 'planning:write' },
  { methods: ['POST'], path: '/mps/plans/:id/periods', permission: 'planning:write' },
  { methods: ['POST'], path: '/mps/plans/:id/demand-inputs', permission: 'planning:write' },
  { methods: ['POST'], path: '/mrp/runs', permission: 'planning:write' },
  { methods: ['POST'], path: '/mrp/runs/:id/item-policies', permission: 'planning:write' },
  { methods: ['POST'], path: '/mrp/runs/:id/gross-requirements', permission: 'planning:write' },
  { methods: ['POST'], path: '/mrp/runs/:id/load-sales-demand', permission: 'planning:write' },
  { methods: ['POST'], path: '/mrp/runs/:id/compute', permission: 'planning:write' },
  { methods: ['POST'], path: '/mrp/planned-orders/:id/firm', permission: 'planning:write' },
  { methods: ['POST'], path: '/mrp/planned-orders/:id/release', permission: 'planning:write' },
  { methods: ['POST'], path: '/replenishment/policies', permission: 'planning:write' },
  { methods: ['POST'], path: '/kpis/runs', permission: 'planning:write' },
  { methods: ['POST'], path: '/kpis/compute/dashboard', permission: 'planning:write' },
  { methods: ['POST'], path: '/kpis/runs/:id/snapshots', permission: 'planning:write' },
  { methods: ['POST'], path: '/kpis/runs/:id/rollup-inputs', permission: 'planning:write' },
  { methods: ['POST'], path: '/drp/nodes', permission: 'planning:write' },
  { methods: ['POST'], path: '/drp/lanes', permission: 'planning:write' },
  { methods: ['POST'], path: '/drp/runs', permission: 'planning:write' },
  { methods: ['POST'], path: '/drp/runs/:id/periods', permission: 'planning:write' },
  { methods: ['POST'], path: '/drp/runs/:id/item-policies', permission: 'planning:write' },
  { methods: ['POST'], path: '/drp/runs/:id/gross-requirements', permission: 'planning:write' },

  { methods: ['POST'], path: '/lots', permission: 'compliance:write' },
  { methods: ['POST'], path: '/inventory-movement-lines/:id/lots', permission: 'compliance:write' },
  { methods: ['POST'], path: '/recalls/cases', permission: 'compliance:admin' },
  { methods: ['PATCH'], path: '/recalls/cases/:id', permission: 'compliance:admin' },
  { methods: ['POST'], path: '/recalls/cases/:id/targets', permission: 'compliance:admin' },
  { methods: ['POST'], path: '/recalls/cases/:id/trace-runs', permission: 'compliance:admin' },
  { methods: ['POST'], path: '/recalls/trace-runs/:id/impacted-shipments', permission: 'compliance:admin' },
  { methods: ['POST'], path: '/recalls/trace-runs/:id/impacted-lots', permission: 'compliance:admin' },
  { methods: ['POST'], path: '/recalls/cases/:id/actions', permission: 'compliance:admin' },
  { methods: ['POST'], path: '/recalls/cases/:id/communications', permission: 'compliance:admin' },

  { methods: ['POST'], path: '/metrics/compute/abc-classification', permission: 'reports:write' },
  { methods: ['POST'], path: '/metrics/compute/slow-dead-stock', permission: 'reports:write' },
  { methods: ['POST'], path: '/metrics/compute/turns-doi', permission: 'reports:write' },
  { methods: ['POST'], path: '/metrics/compute/all', permission: 'reports:write' },
  { methods: ['POST'], path: '/metrics/cache/invalidate', permission: 'reports:write' },
  { methods: ['POST'], path: '/metrics/job/trigger', permission: 'reports:write' },
  { methods: ['POST'], path: '/atp/check', permission: 'inventory:read' },

  // --- Sensitive GET read routes ---

  // Inventory reads
  { methods: ['GET'], path: '/inventory-movements', permission: 'inventory:read' },
  { methods: ['GET'], path: '/inventory-movements/window', permission: 'inventory:read' },
  { methods: ['GET'], path: '/inventory-movements/:id', permission: 'inventory:read' },
  { methods: ['GET'], path: '/inventory-movements/:id/lines', permission: 'inventory:read' },
  { methods: ['GET'], path: '/inventory-movements/:id/lots', permission: 'inventory:read' },
  { methods: ['GET'], path: '/inventory-adjustments', permission: 'inventory:read' },
  { methods: ['GET'], path: '/inventory-adjustments/:id', permission: 'inventory:read' },
  { methods: ['GET'], path: '/inventory-counts', permission: 'inventory:read' },
  { methods: ['GET'], path: '/inventory-counts/:id', permission: 'inventory:read' },
  { methods: ['GET'], path: '/inventory-snapshot', permission: 'inventory:read' },
  { methods: ['GET'], path: '/inventory-snapshot/summary', permission: 'inventory:read' },
  { methods: ['GET'], path: '/inventory/changes', permission: 'inventory:read' },
  { methods: ['GET'], path: '/putaways/:id', permission: 'inventory:read' },
  { methods: ['GET'], path: '/items/:id/inventory', permission: 'inventory:read' },
  { methods: ['GET'], path: '/locations/:id/inventory', permission: 'inventory:read' },
  { methods: ['GET'], path: '/lpns', permission: 'inventory:read' },
  { methods: ['GET'], path: '/lpns/:id', permission: 'inventory:read' },
  { methods: ['GET'], path: '/atp', permission: 'inventory:read' },
  { methods: ['GET'], path: '/atp/detail', permission: 'inventory:read' },
  { methods: ['GET'], path: '/events', permission: 'inventory:read' },
  { methods: ['GET'], path: '/events/clients', permission: 'inventory:read' },

  // Purchasing reads
  { methods: ['GET'], path: '/purchase-orders', permission: 'purchasing:read' },
  { methods: ['GET'], path: '/purchase-orders/:id', permission: 'purchasing:read' },
  { methods: ['GET'], path: '/purchase-order-receipts', permission: 'purchasing:read' },
  { methods: ['GET'], path: '/purchase-order-receipts/:id', permission: 'purchasing:read' },
  { methods: ['GET'], path: '/purchase-order-receipts/:id/reconciliation', permission: 'purchasing:read' },
  { methods: ['GET'], path: '/vendors', permission: 'purchasing:read' },
  { methods: ['GET'], path: '/supplier-scorecards', permission: 'purchasing:read' },
  { methods: ['GET'], path: '/supplier-scorecards/:vendorId', permission: 'purchasing:read' },
  { methods: ['GET'], path: '/supplier-scorecards/rankings/delivery', permission: 'purchasing:read' },
  { methods: ['GET'], path: '/supplier-scorecards/rankings/quality', permission: 'purchasing:read' },
  { methods: ['GET'], path: '/supplier-scorecards/issues/quality', permission: 'purchasing:read' },
  { methods: ['GET'], path: '/supplier-performance/lead-time-reliability', permission: 'purchasing:read' },
  { methods: ['GET'], path: '/supplier-performance/price-variance-trends', permission: 'purchasing:read' },
  { methods: ['GET'], path: '/supplier-performance/vendor-fill-rate', permission: 'purchasing:read' },
  { methods: ['GET'], path: '/supplier-performance/quality-rate', permission: 'purchasing:read' },

  // Finance reads
  { methods: ['GET'], path: '/vendor-invoices', permission: 'finance:read' },
  { methods: ['GET'], path: '/vendor-invoices/:id', permission: 'finance:read' },
  { methods: ['GET'], path: '/vendor-payments', permission: 'finance:read' },
  { methods: ['GET'], path: '/vendor-payments/:id', permission: 'finance:read' },
  { methods: ['GET'], path: '/vendors/:vendorId/unpaid-invoices', permission: 'finance:read' },
  { methods: ['GET'], path: '/api/currencies', permission: 'finance:read' },
  { methods: ['GET'], path: '/api/exchange-rates', permission: 'finance:read' },

  // Production reads
  { methods: ['GET'], path: '/work-orders', permission: 'production:read' },
  { methods: ['GET'], path: '/work-orders/:id', permission: 'production:read' },
  { methods: ['GET'], path: '/work-orders/:id/requirements', permission: 'production:read' },
  { methods: ['GET'], path: '/work-orders/:id/readiness', permission: 'production:read' },
  { methods: ['GET'], path: '/work-orders/:id/disassembly-plan', permission: 'production:read' },
  { methods: ['GET'], path: '/work-orders/:id/issues/:issueId', permission: 'production:read' },
  { methods: ['GET'], path: '/work-orders/:id/completions/:completionId', permission: 'production:read' },
  { methods: ['GET'], path: '/work-orders/:id/execution', permission: 'production:read' },
  { methods: ['GET'], path: '/work-orders/:id/qc-events', permission: 'production:read' },
  { methods: ['GET'], path: '/work-order-execution-lines/:id/qc-events', permission: 'production:read' },
  { methods: ['GET'], path: '/boms/:id', permission: 'production:read' },
  { methods: ['GET'], path: '/items/:id/boms', permission: 'production:read' },
  { methods: ['GET'], path: '/items/:id/next-step-boms', permission: 'production:read' },
  { methods: ['GET'], path: '/items/:id/bom', permission: 'production:read' },
  { methods: ['GET'], path: '/work-centers', permission: 'production:read' },
  { methods: ['GET'], path: '/work-centers/:id', permission: 'production:read' },
  { methods: ['GET'], path: '/items/:itemId/routings', permission: 'production:read' },
  { methods: ['GET'], path: '/routings/:id', permission: 'production:read' },
  { methods: ['GET'], path: '/production-overview', permission: 'production:read' },
  { methods: ['GET'], path: '/production-overview/volume-trend', permission: 'production:read' },
  { methods: ['GET'], path: '/production-overview/top-bottom-skus', permission: 'production:read' },
  { methods: ['GET'], path: '/production-overview/wip-status', permission: 'production:read' },
  { methods: ['GET'], path: '/production-overview/materials-consumed', permission: 'production:read' },

  // Outbound reads
  { methods: ['GET'], path: '/sales-orders', permission: 'outbound:read' },
  { methods: ['GET'], path: '/sales-orders/:id', permission: 'outbound:read' },
  { methods: ['GET'], path: '/reservations', permission: 'outbound:read' },
  { methods: ['GET'], path: '/reservations/:id', permission: 'outbound:read' },
  { methods: ['GET'], path: '/shipments', permission: 'outbound:read' },
  { methods: ['GET'], path: '/shipments/:id', permission: 'outbound:read' },
  { methods: ['GET'], path: '/returns', permission: 'outbound:read' },
  { methods: ['GET'], path: '/returns/:id', permission: 'outbound:read' },
  { methods: ['GET'], path: '/return-receipts', permission: 'outbound:read' },
  { methods: ['GET'], path: '/return-receipts/:id', permission: 'outbound:read' },
  { methods: ['GET'], path: '/return-dispositions', permission: 'outbound:read' },
  { methods: ['GET'], path: '/return-dispositions/:id', permission: 'outbound:read' },
  { methods: ['GET'], path: '/pick-batches', permission: 'outbound:read' },
  { methods: ['GET'], path: '/pick-batches/:id', permission: 'outbound:read' },
  { methods: ['GET'], path: '/pick-tasks', permission: 'outbound:read' },
  { methods: ['GET'], path: '/pick-tasks/:id', permission: 'outbound:read' },
  { methods: ['GET'], path: '/shipping-containers', permission: 'outbound:read' },
  { methods: ['GET'], path: '/shipping-containers/:id', permission: 'outbound:read' },

  // Compliance reads
  { methods: ['GET'], path: '/ncrs', permission: 'compliance:read' },
  { methods: ['GET'], path: '/ncrs/:id', permission: 'compliance:read' },
  { methods: ['GET'], path: '/lots', permission: 'compliance:read' },
  { methods: ['GET'], path: '/lots/:id', permission: 'compliance:read' },
  { methods: ['GET'], path: '/inventory-movement-lines/:id/lots', permission: 'compliance:read' },
  { methods: ['GET'], path: '/purchase-order-receipt-lines/:id/qc-events', permission: 'compliance:read' },
  { methods: ['GET'], path: '/qc-events/:id', permission: 'compliance:read' },
  { methods: ['GET'], path: '/recalls/cases', permission: 'compliance:read' },
  { methods: ['GET'], path: '/recalls/cases/:id', permission: 'compliance:read' },
  { methods: ['GET'], path: '/recalls/cases/:id/targets', permission: 'compliance:read' },
  { methods: ['GET'], path: '/recalls/cases/:id/trace-runs', permission: 'compliance:read' },
  { methods: ['GET'], path: '/recalls/cases/:id/actions', permission: 'compliance:read' },
  { methods: ['GET'], path: '/recalls/cases/:id/communications', permission: 'compliance:read' },
  { methods: ['GET'], path: '/recalls/trace-runs/:id', permission: 'compliance:read' },
  { methods: ['GET'], path: '/recalls/trace-runs/:id/impacted-shipments', permission: 'compliance:read' },
  { methods: ['GET'], path: '/recalls/trace-runs/:id/impacted-lots', permission: 'compliance:read' },

  // Master data reads
  { methods: ['GET'], path: '/items', permission: 'masterdata:read' },
  { methods: ['GET'], path: '/items/:id', permission: 'masterdata:read' },
  { methods: ['GET'], path: '/items/:id/metrics', permission: 'masterdata:read' },
  { methods: ['GET'], path: '/locations', permission: 'masterdata:read' },
  { methods: ['GET'], path: '/locations/:id', permission: 'masterdata:read' },
  { methods: ['GET'], path: '/uoms', permission: 'masterdata:read' },
  { methods: ['GET'], path: '/items/:itemId/uom-conversions', permission: 'masterdata:read' },

  // Planning reads
  { methods: ['GET'], path: '/mps/plans', permission: 'planning:read' },
  { methods: ['GET'], path: '/mps/plans/:id', permission: 'planning:read' },
  { methods: ['GET'], path: '/mps/plans/:id/periods', permission: 'planning:read' },
  { methods: ['GET'], path: '/mps/plans/:id/demand-inputs', permission: 'planning:read' },
  { methods: ['GET'], path: '/mps/plans/:id/plan-lines', permission: 'planning:read' },
  { methods: ['GET'], path: '/mrp/runs', permission: 'planning:read' },
  { methods: ['GET'], path: '/mrp/runs/:id', permission: 'planning:read' },
  { methods: ['GET'], path: '/mrp/runs/:id/item-policies', permission: 'planning:read' },
  { methods: ['GET'], path: '/mrp/runs/:id/gross-requirements', permission: 'planning:read' },
  { methods: ['GET'], path: '/mrp/runs/:id/plan-lines', permission: 'planning:read' },
  { methods: ['GET'], path: '/mrp/runs/:id/planned-orders', permission: 'planning:read' },
  { methods: ['GET'], path: '/replenishment/policies', permission: 'planning:read' },
  { methods: ['GET'], path: '/replenishment/policies/:id', permission: 'planning:read' },
  { methods: ['GET'], path: '/replenishment/recommendations', permission: 'planning:read' },
  { methods: ['GET'], path: '/kpis/runs', permission: 'planning:read' },
  { methods: ['GET'], path: '/kpis/runs/:id', permission: 'planning:read' },
  { methods: ['GET'], path: '/kpis/fulfillment-fill-rate', permission: 'planning:read' },
  { methods: ['GET'], path: '/kpis/runs/:id/snapshots', permission: 'planning:read' },
  { methods: ['GET'], path: '/kpis/snapshots', permission: 'planning:read' },
  { methods: ['GET'], path: '/kpis/runs/:id/rollup-inputs', permission: 'planning:read' },
  { methods: ['GET'], path: '/drp/nodes', permission: 'planning:read' },
  { methods: ['GET'], path: '/drp/nodes/:id', permission: 'planning:read' },
  { methods: ['GET'], path: '/drp/lanes', permission: 'planning:read' },
  { methods: ['GET'], path: '/drp/lanes/:id', permission: 'planning:read' },
  { methods: ['GET'], path: '/drp/runs', permission: 'planning:read' },
  { methods: ['GET'], path: '/drp/runs/:id', permission: 'planning:read' },
  { methods: ['GET'], path: '/drp/runs/:id/periods', permission: 'planning:read' },
  { methods: ['GET'], path: '/drp/runs/:id/item-policies', permission: 'planning:read' },
  { methods: ['GET'], path: '/drp/runs/:id/gross-requirements', permission: 'planning:read' },
  { methods: ['GET'], path: '/drp/runs/:id/plan-lines', permission: 'planning:read' },
  { methods: ['GET'], path: '/drp/runs/:id/planned-transfers', permission: 'planning:read' },

  // Reports and metrics reads
  { methods: ['GET'], path: '/reports/inventory-valuation', permission: 'reports:read' },
  { methods: ['GET'], path: '/reports/cost-variance', permission: 'reports:read' },
  { methods: ['GET'], path: '/reports/receipt-cost-analysis', permission: 'reports:read' },
  { methods: ['GET'], path: '/reports/work-order-progress', permission: 'reports:read' },
  { methods: ['GET'], path: '/reports/movement-transactions', permission: 'reports:read' },
  { methods: ['GET'], path: '/reports/inventory-velocity', permission: 'reports:read' },
  { methods: ['GET'], path: '/reports/open-po-aging', permission: 'reports:read' },
  { methods: ['GET'], path: '/reports/sales-order-fill', permission: 'reports:read' },
  { methods: ['GET'], path: '/reports/production-run-frequency', permission: 'reports:read' },
  { methods: ['GET'], path: '/reports/bom-consumption-variance', permission: 'reports:read' },
  { methods: ['GET'], path: '/reports/yield-variance', permission: 'reports:read' },
  { methods: ['GET'], path: '/reports/execution-summary', permission: 'reports:read' },
  { methods: ['GET'], path: '/metrics/abc-classification', permission: 'reports:read' },
  { methods: ['GET'], path: '/metrics/inventory-aging', permission: 'reports:read' },
  { methods: ['GET'], path: '/metrics/slow-dead-stock', permission: 'reports:read' },
  { methods: ['GET'], path: '/metrics/turns-doi', permission: 'reports:read' },
  { methods: ['GET'], path: '/metrics/cache/stats', permission: 'reports:write' },
  { methods: ['GET'], path: '/metrics/job/status', permission: 'reports:write' },
  { methods: ['GET'], path: '/api/dashboard/overview', permission: 'reports:read' },
  { methods: ['GET'], path: '/api/dashboard/inventory-integrity', permission: 'reports:read' },
  { methods: ['GET'], path: '/api/dashboard/inventory-risk', permission: 'reports:read' },
  { methods: ['GET'], path: '/api/dashboard/inventory-coverage', permission: 'reports:read' },
  { methods: ['GET'], path: '/api/dashboard/flow-reliability', permission: 'reports:read' },
  { methods: ['GET'], path: '/api/dashboard/supply-reliability', permission: 'reports:read' },
  { methods: ['GET'], path: '/api/dashboard/excess-inventory', permission: 'reports:read' },
  { methods: ['GET'], path: '/api/dashboard/demand-volatility', permission: 'reports:read' },
  { methods: ['GET'], path: '/api/dashboard/forecast-accuracy', permission: 'reports:read' },
  { methods: ['GET'], path: '/api/dashboard/system-readiness', permission: 'reports:read' },
  { methods: ['GET'], path: '/api/dashboard/performance-metrics', permission: 'reports:read' },

  // Cost layer reads
  { methods: ['GET'], path: '/api/cost-layers/item/:itemId', permission: 'costlayers:read' },
  { methods: ['GET'], path: '/api/cost-layers/available', permission: 'costlayers:read' },
  { methods: ['GET'], path: '/api/cost-layers/average-cost', permission: 'costlayers:read' },
  { methods: ['GET'], path: '/api/cost-layers/:layerId/consumptions', permission: 'costlayers:read' },
  { methods: ['GET'], path: '/api/cost-layers/cogs', permission: 'costlayers:read' },
  { methods: ['GET'], path: '/api/items/:id/cost-history', permission: 'costlayers:read' }
] as const satisfies readonly RoutePermissionRule[];

