import type { MigrationBuilder } from 'node-pg-migrate';

type EnsureCheckConstraintOptions = {
  schema?: string;
  table: string;
  constraintName: string;
  checkExpression: string;
};

function assertIdentifier(value: string, field: string): string {
  if (!/^[a-zA-Z_][a-zA-Z0-9_]*$/.test(value)) {
    throw new Error(`MIGRATION_IDENTIFIER_INVALID field=${field} value=${value}`);
  }
  return value;
}

function quoteIdentifier(value: string): string {
  return `"${value.replace(/"/g, '""')}"`;
}

function quoteLiteral(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

/**
 * Ensure a CHECK constraint exists with the exact canonical definition generated by PostgreSQL
 * for the provided checkExpression. If the same constraint name exists with a different definition,
 * fail loud instead of silently accepting drift.
 */
export function ensureCheckConstraintIfMissingOrFail(
  pgm: MigrationBuilder,
  options: EnsureCheckConstraintOptions
): void {
  const schema = assertIdentifier(options.schema ?? 'public', 'schema');
  const table = assertIdentifier(options.table, 'table');
  const constraintName = assertIdentifier(options.constraintName, 'constraintName');
  const probeTable = '__constraint_def_probe_locations';
  const probeConstraint = '__constraint_def_probe_check';

  const targetRelation = `${quoteIdentifier(schema)}.${quoteIdentifier(table)}`;

  pgm.sql(`
DO $$
DECLARE
  existing_def text;
  expected_def text;
  normalized_existing text;
  normalized_expected text;
BEGIN
  SELECT pg_get_constraintdef(c.oid)
    INTO existing_def
    FROM pg_constraint c
    JOIN pg_class t
      ON t.oid = c.conrelid
    JOIN pg_namespace n
      ON n.oid = t.relnamespace
   WHERE n.nspname = ${quoteLiteral(schema)}
     AND t.relname = ${quoteLiteral(table)}
     AND c.conname = ${quoteLiteral(constraintName)};

  CREATE TEMP TABLE IF NOT EXISTS ${quoteIdentifier(probeTable)} (
    LIKE ${targetRelation}
    INCLUDING DEFAULTS
    INCLUDING GENERATED
    INCLUDING IDENTITY
  ) ON COMMIT DROP;

  ALTER TABLE ${quoteIdentifier(probeTable)}
    DROP CONSTRAINT IF EXISTS ${quoteIdentifier(probeConstraint)};

  ALTER TABLE ${quoteIdentifier(probeTable)}
    ADD CONSTRAINT ${quoteIdentifier(probeConstraint)}
    CHECK (${options.checkExpression});

  SELECT pg_get_constraintdef(c.oid)
    INTO expected_def
    FROM pg_constraint c
    JOIN pg_class t
      ON t.oid = c.conrelid
    JOIN pg_namespace n
      ON n.oid = t.relnamespace
   WHERE n.oid = pg_my_temp_schema()
     AND t.relname = ${quoteLiteral(probeTable)}
     AND c.conname = ${quoteLiteral(probeConstraint)};

  IF expected_def IS NULL THEN
    RAISE EXCEPTION 'CONSTRAINT_PROBE_DEFINITION_MISSING constraint=% table=%.%',
      ${quoteLiteral(constraintName)},
      ${quoteLiteral(schema)},
      ${quoteLiteral(table)};
  END IF;

  IF existing_def IS NULL THEN
    EXECUTE format(
      $fmt$ALTER TABLE %I.%I ADD CONSTRAINT %I CHECK (${options.checkExpression})$fmt$,
      ${quoteLiteral(schema)},
      ${quoteLiteral(table)},
      ${quoteLiteral(constraintName)}
    );
    RETURN;
  END IF;

  normalized_existing := regexp_replace(lower(existing_def), '\\s+', '', 'g');
  normalized_expected := regexp_replace(lower(expected_def), '\\s+', '', 'g');

  IF normalized_existing <> normalized_expected THEN
    RAISE EXCEPTION 'CONSTRAINT_DEFINITION_MISMATCH constraint=% table=%.% existing=% expected=%',
      ${quoteLiteral(constraintName)},
      ${quoteLiteral(schema)},
      ${quoteLiteral(table)},
      existing_def,
      expected_def;
  END IF;
END
$$;
  `);
}
